In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'/Users/bilegjargalbattulga/Desktop/data analyst/Python for Dana Analysis/Group By and Aggregating/banking.csv'
                , encoding = 'ISO-8859-1')

In [3]:
df

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan
0,58,management,married,tertiary,no,2143,yes,no
1,44,technician,single,secondary,no,29,yes,no
2,33,entrepreneur,married,secondary,no,2,yes,yes
3,47,blue-collar,married,unknown,no,1506,yes,no
4,33,unknown,single,unknown,no,1,no,no
...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no
45207,71,retired,divorced,primary,no,1729,no,no
45208,72,retired,married,secondary,no,5715,no,no
45209,57,blue-collar,married,secondary,no,668,no,no
45210,37,entrepreneur,married,secondary,no,2971,no,no

In [4]:
df.groupby(['job', 'marital'])['outstanding_balance'].sum()

job            marital
admin.         divorced     658750
               married     3450836
               single      1763837
blue-collar    divorced     615605
               married     7756540
               single      2126996
entrepreneur   divorced     206921
               married     1758425
               single       297080
housemaid      divorced     289473
               married     1138334
               single       298763
management     divorced    1797680
               married     9872061
               single      5010547
retired        divorced     640830
               married     3704511
               single       146922
self-employed  divorced     339689
               married     1633434
               single       629023
services       divorced     458033
               married     2620856
               single      1063015
student        divorced       6606
               married       62899
               single      1232496
technician     divorced     854745
               married     5297583
               single      3363918
unemployed     divorced     241049
               married     1146670
               single       595116
unknown        divorced      29007
               married      362990
               single       118442
Name: outstanding_balance, dtype: int64

In [6]:
#filtering down only on management

In [5]:
df[df['job'] == 'management'].groupby(['job', 'marital'])['outstanding_balance'].sum()

job         marital
management  divorced    1797680
            married     9872061
            single      5010547
Name: outstanding_balance, dtype: int64

In [8]:
new_df = df.groupby(['education', 'personal_loan'])['outstanding_balance'].mean()

In [10]:
# changing to dataframe

In [9]:
new_df.reset_index()

   education personal_loan  outstanding_balance
0    primary            no          1360.122361
1    primary           yes           629.711914
2  secondary            no          1254.733531
3  secondary           yes           716.322333
4   tertiary            no          1875.620995
5   tertiary           yes          1001.776906
6    unknown            no          1589.566125
7    unknown           yes           712.563910